### ISSUE TITLE
Would it be possible for w3champions  to get translated?

### ISSUE THREAD

**Issue by 411752230** [w3champions/launcher#100]
Gladly to help translate it into Simplified Chinese. :)

**Comment by modmoto** [comment]
oh jeah, especially chinese is a good idea. I wanted to do some work on it the next days and translating it would be cool. We just talk here then? Or are you on our discord?

**Comment by 411752230** [comment]
> oh jeah, especially chinese is a good idea. I wanted to do some work on it the next days and translating it would be cool. We just talk here then? Or are you on our discord?

I have just joined the channel for a while.

**Comment by zygissss** [comment]
done
