### ISSUE TITLE
Error Entering the Queue

### ISSUE THREAD

**Issue by erfanmola** [w3champions/launcher#101]
Hi, I am facing this error :
![](https://s18.picofile.com/file/8438558684/WC3ScrnShot_072621_064532_001.png)

I am using :
W3Champions Version : 24
Launcher Version : 0.17.0
Warcraft 3 : 1.32.10.17380

Here is [main.log](https://pastebin.ubuntu.com/p/qsvGFHPygQ/)
And here is [renderer.log](https://pastebin.ubuntu.com/p/39dhqwjjM5/)

And need to mention, I am from Iran, So the nearest Server to me is Europe and Im using Europe Region

**Comment by abeninskibede** [comment]
Hey,
Thanks for reporting.

Unfortunately Iran blocks some of the western internet traffick and flo is included. You should try using a VPN. Other iranians have been able to bypass it. You may try asking them

**Comment by erfanmola** [comment]
> Hey,
> 
> Thanks for reporting.
> 
> 
> 
> Unfortunately Iran blocks some of the western internet traffick and flo is included. You should try using a VPN. Other iranians have been able to bypass it. You may try asking them

What are servers address ? So i could talk to government for reconsideration

**Comment by abeninski** [comment]
Did you find any workarround?

**Comment by erfanmola** [comment]
> Did you find any workarround?

I setup a VPN Server on my VPS in Iran, my VPS seemed to have no issues with Flo, and it worked on my system too, as long as I tunnel my connection through my VPS

And since my ping to my VPS is around 10ms, it has no big latency impact

**Comment by abeninski** [comment]
Right. Thanks for the response
