### ISSUE TITLE
Show assistance in launcher if flo is not connected

### ISSUE THREAD

**Issue by marcoabreu** [w3champions/launcher#102]
If flo is not connected, don't allow to use the "Play" button in the launcher. Instead, interact with the flo worker to determine why it's not connecting. One example:

```
[2021-08-21 15:19:16.378] [info] {"type":"Disconnect","reason":"Multi","message":"Server closed the connection: 1"}
```

Reason here was that I was logged into w3c with two computers using the same battle-net id. These kinds of messages should be bubbled up to the UI so the users can take appropriate action.

**Comment by zygissss** [comment]
done
