### ISSUE TITLE
Inventory hotkeys not working on macOS

### ISSUE THREAD

**Issue by weckbach** [w3champions/launcher#111]
Hey Team,

it seems to me that the MacOs Inventory hotkeys are not working. I assigned the inventory hotkeys to Shift + qwaszx, but in-game it never works. I'm on macOS Mojave 10.14.6. Let me know if you need further information, or if this is a common limitation. From the codebase, it looks like it should be supported.

Thanks in advance,
Volker

**Comment by githubfellow87123** [comment]
Same here macOS Monterey 12.4.
