### ISSUE TITLE
Can someone help me with troubleshooting this issue? I am not tech savvy but would like to play this game. Thanks!

### ISSUE THREAD

**Issue by mrjablonsky** [w3champions/launcher#116]
![Screen Shot 2022-06-29 at 10 16 00 AM](https://user-images.githubusercontent.com/108414677/176461074-1f7af7e1-48ff-457b-a1d3-ed60b2d50946.png)

Getting this error message when I try to start a 4v4 game. Tried restarting the battlenet launcher and I have wc3 running in the background. Using a Mac. Your help would be greatly appreciated. Miss playing this game.

**Comment by gDollaZ** [comment]
This usually indicates that the correct permissions have not been granted to the W3Champions app.
You can grant these permissions under:
System Preferences > Privacy and Security > Privacy tab.
You will need to look through each Group on the left hand side and if W3Champions is listed, click the checkbox.
 
If you still need further assistance,  post a message in #i-need-help in the discord channel.
