### ISSUE TITLE
why the map icon cannot Offline operation

### ISSUE THREAD

**Issue by jzy-chitong56** [w3champions/launcher#141]
now the map have some new item and NEUTRAL build icon , I open the map , the icon file is existence

but if no run the W3C launcher , just Offline or online battlenet , Including map conversion to JASS ，the icon all cannot normal display

why , the file should be can support Offline , it do not like a custom map?

**Comment by BogdanW3** [comment]
All the specific map icon stuff is tied to the maps themselves, currently there is no launcher component to this.
**Trying** to convert them to Jass will of course **remove all** the custom triggers that power these systems as well as possibly even removing the assets needed for this depending on how bad the converter is.
If you'd like a more technical background, we use w3t files for item icons and typescript->Lua to make the neutral building icons, both also using special assets of the icons themselves.
I can't recommend trying to mess with them too much unless you know exactly what you're doing.

**Comment by jzy-chitong56** [comment]
> All the specific map icon stuff is tied to the maps themselves, currently there is no launcher component to this. **Trying** to convert them to Jass will of course **remove all** the custom triggers that power these systems as well as possibly even removing the assets needed for this depending on how bad the converter is. If you'd like a more technical background, we use w3t files for item icons and typescript->Lua to make the neutral building icons, both also using special assets of the icons themselves. I can't recommend trying to mess with them too much unless you know exactly what you're doing.

yes , i know the neutral building icons, use lua , and I try use jass triggers go use them , but I failed.
and the item icons , you said them is w3t , should donot need lua??  but when map conversion to JASS , them invalid , just have green icon , so this is I donot know why

**Comment by BogdanW3** [comment]
If you're trying to take these maps to an old version, that won't work at all. And Jass is also incapable of using this system due to the array size it has.
