### ISSUE TITLE
Question: How do you change ingame UI of WC3

### ISSUE THREAD

**Issue by frosk1** [w3champions/launcher#152]
Hey,

I would love to get involved in the project. Therefore I am wondering how you are changing the ingame UI by not only changing background of the main menu in wc3, but also adding buttons and new views? I think this is not just done by changing .mdx files is it?

**Comment by frosk1** [comment]
I am a data scientist and could help building an machine learning (ai) driven matchmaking system model, if interest is there. But would be intersted in the architecture of w3champions first, do you sniff packets from wc3 network traffic to get information about the game and how to change ingame UI this feels strange to me how this works.

**Comment by BogdanW3** [comment]
Warcraft 3 allows changing some of the game's internal data via [Local Files](https://www.hiveworkshop.com/threads/local-files.330849/), you might find something useful there. What W3Champions does is work with some of the webui, but the specifics are very complicated and hard to implement. Feel free to tinker around with the html and js files in the game data (use [CascView](http://www.zezula.net/en/casc/main.html) to access them) and see if you find anything useful for your goals.

**Comment by paulo101977** [comment]
> Warcraft 3 allows changing some of the game's internal data via [Local Files](https://www.hiveworkshop.com/threads/local-files.330849/), you might find something useful there. What W3Champions does is work with some of the webui, but the specifics are very complicated and hard to implement. Feel free to tinker around with the html and js files in the game data (use [CascView](http://www.zezula.net/en/casc/main.html) to access them) and see if you find anything useful for your goals.

I always wondered if there was some user-friendly way to create an external AI and train it to replace the game's normal AI (which is pretty dumb).

**Comment by BogdanW3** [comment]
> > Warcraft 3 allows changing some of the game's internal data via [Local Files](https://www.hiveworkshop.com/threads/local-files.330849/), you might find something useful there. What W3Champions does is work with some of the webui, but the specifics are very complicated and hard to implement. Feel free to tinker around with the html and js files in the game data (use [CascView](http://www.zezula.net/en/casc/main.html) to access them) and see if you find anything useful for your goals.
> 
> I always wondered if there was some user-friendly way to create an external AI and train it to replace the game's normal AI (which is pretty dumb).

The ingame AI can't be replaced easily, unlike Starcraft's support, War3 doesn't offer anything to interact with the game itself externally. The best you could do is code up something in Jass as the AI is powered by Jass scripts, and put that into a map to test it out

That was a bit off-topic though, and since the topic got answered, I'll close the issue now. Good luck to you both with your projects!
