### ISSUE TITLE
W3Champions Ladder Error

### ISSUE THREAD

**Issue by gyxtcgyxtc** [w3champions/launcher#179]
Says "You are not yet authorized on the W3Champions server. Try again in a few minutes. "

Even after I had uninstalled all W3C (new and old) from my PC, and launch War3 from BattleNet, I am still getting this error pop-up(or drop-down to be more precise) every 3 seconds. It is really annoying. Any idea why this is happening?

**Comment by BogdanW3** [comment]
The uninstaller for the old launcher doesn't yet remove the webui modification, you can remove it manually as Death said, but the authorization error itself has been mitigated now
