### ISSUE TITLE
Inventory hotkeys sometimes accidentally turn on/off

### ISSUE THREAD

**Issue by abeninski** [w3champions/launcher#26]
Inventory hotkeys sometimes do not work or turn off automatically.
We need a way to force hotkeys to stay always on.

**Comment by marco93f** [comment]
I'm experiencing the opposite issue. I play with a custom AHK script, so I have disabled inventory hotkeys from the launcher, otherwise the latter overrides the former. Yet, sometimes they activate for whatever reason (not because of the on/off hotkey).

**Comment by modmoto** [comment]
the turn on/off when you enter a game. At least they should. I will take a look at an item that is clickable and always on top. Electron can do this somehow.

**Comment by arcsaber** [comment]
The autoturn on/off function is lost when a player restarts wc3 but not the launcher. After restarting wc3 the hotkey script remains in its previous state (on or off, depending on where you closed wc3) until you manually toggle it.

**Comment by modmoto** [comment]
We have the option to turn on/off always, so this should okish. There are still some holes for edgecases like alt/tab, but I guess this is how it stays for now. Will close it as it is a little old now.

**Comment by clauderoy790** [comment]
I'm having the same issue using MacOS Monterey 12.2.1 and using W3C app Version 0.17.1 (0.17.1.20210727.2).
Even if I turn on the inventory hotkey, the next time that I open the app, they will be off. That said, I'm able to set custom hotkeys and those work properly.
