### ISSUE TITLE
Hotkey for "Cancel" is not writing correctly

### ISSUE THREAD

**Issue by Cepheid-UK** [w3champions/launcher#66]
When players use the launcher to write a customkeys.txt, the key codes for cancel (27 or sometimes 512, language dependent) are truncated to "2" and "5" respectively, the player then has to go and edit the customkeys.txt manually.

**Comment by modmoto** [comment]
@Cepheid-UK wanted to finally tackle this again. Do you know how this is actually working? like 27, 512 or whatever else is now a correct cancel button? You know someone that knows this for all languages?

**Comment by Cepheid-UK** [comment]
Not sure @arcsaber knows better.

**Comment by arcsaber** [comment]
It should be fixed, but after it got fixed I got 1-2 reports of this bug. They might have had an old launcher version though or a "legacy" hotkey file.

**Comment by modmoto** [comment]
ok, so closing this one then. lets see if someone complains again
