### ISSUE TITLE
orc units hotkeys purge: check if it apg2 or aprg

### ISSUE THREAD

**Issue by Qeenon** [w3champions/launcher#74]
some user in chat used to complain
just someone needs to check if it's aprg or apg2

**Comment by modmoto** [comment]
Ah thanks, I was doing some work on the launcher now and wanted to fix a few keys. Will check that then.

**Comment by modmoto** [comment]
it is aprg and is working for me here, but thanks for the heads up!

**Comment by Qeenon** [comment]
![image](https://user-images.githubusercontent.com/38455533/105352907-fb905a00-5c07-11eb-9abf-7d72954c7969.png)

okay, if you sure, there were complain

**Comment by modmoto** [comment]
I just testes it with the live version. But this seems quite recent 14.1?

**Comment by Qeenon** [comment]
y

**Comment by Qeenon** [comment]
@modmoto don't know how you've tested, it's wrong, apg2 is correct

**Comment by modmoto** [comment]
well, how did you test it? 
I think apg2 is for neutral creep purge, but on my wc3 it is definitly not for the shaman.

![Untitled3](https://user-images.githubusercontent.com/9074759/106414219-60d81c80-644c-11eb-9194-7f019ac2ce21.png)
![Capture](https://user-images.githubusercontent.com/9074759/106414223-63d30d00-644c-11eb-9f7c-338672a53c0c.JPG)
![Untitled](https://user-images.githubusercontent.com/9074759/106414225-63d30d00-644c-11eb-9313-db62be5c6436.png)
![Capture2](https://user-images.githubusercontent.com/9074759/106414232-66356700-644c-11eb-85c8-18b4d07fceed.JPG)

**Comment by Qeenon** [comment]
@modmoto I have English locale for game, what I did to test: changed apg2 to `Z`, created custom game vs computer, build shaman, check purge, it was 'Z'. It's strange that for you it's different but there are two reports on chat and my test.
Please try testing in custom ladder game.

**Comment by modmoto** [comment]
You want to share your hk file? Did you make sure that there is no aprg defined in there? I also run on english.

**Comment by modmoto** [comment]
`Ability.MultiHotkey('Purge', 'btnpurge', 'aprg', 'G', [], ['apg2']),`

this would just write both hks, if we need that for whatever reason.

**Comment by modmoto** [comment]
i just started a online CG and there apg2 also works for me. I will just add the double HK to be save

**Comment by modmoto** [comment]
https://github.com/w3champions/launcher/commit/88bf5b84f1a9064af9c548c7256f388fea07416f

**Comment by Qeenon** [comment]
good
