### ISSUE TITLE
Hotkeys: Additional merc camps on RT maps and boats

### ISSUE THREAD

**Issue by arcsaber** [w3champions/launcher#78]
- featherville is one of them, it has ogre magi and gnolls @merccamp
- dalaran garden +  phantom grove have the merc camp with bandits/kobolds
- vile reef is the boat map i think, really annoying to shift unload with L

**Comment by gustav87** [comment]
Won't do for now. If someone wants to configure a seldom used hotkey, they can edit the customkeys file themselves. It won't benefit very many users, and you might add some unit to the hotkey (like boat), and then that map is rotated out, leaving the hotkey obsolete.
