### ISSUE TITLE
Maybe there's a way to support wooden pcs?

### ISSUE THREAD

**Issue by arcsaber** [w3champions/launcher#79]
The window is too large and font too small, according to this user.

![unknow11n](https://user-images.githubusercontent.com/24671173/105644400-a5d0e180-5e95-11eb-94c0-2df25ab231da.png)

**Comment by modmoto** [comment]
what is his resolution?

**Comment by arcsaber** [comment]
1380х768

**Comment by modmoto** [comment]
ok, will give this a try. But I dont have high hopes, as the launcher is not that responsive right now.

**Comment by modmoto** [comment]
will not be done, realistically :/
