### ISSUE TITLE
Unable to change Shift+F4 to another Shift/Ctrl/Alt + button combination

### ISSUE THREAD

**Issue by orangeag3nt** [w3champions/launcher#81]
Run launcher, go to hotkeys tab. Press on button for "on/off". Press Shift. Get that message:
"Could not register combo: Ctrl. Switching to an english keyboard layout should help. Nevertheless, please reach out on discord to get this fixed for good =)"

**Comment by modmoto** [comment]
hmm, looks like this is broken for a while. I will check what caused that regression.
