### ISSUE TITLE
Parsing custom keys with custom tips faults

### ISSUE THREAD

**Issue by Qeenon** [w3champions/launcher#85]
Hex was showing up with the default key of X in the GUI, due to it not being able to parse this:
```
// Hex
[AOhx]
Tip=He|cffffcc00x|r - [|cffffcc00Level 1|r],He|cffffcc00x|r -
 [|cffffcc00Level 2|r],He|cffffcc00x|r - [|cffffcc00Level 3|r]
Hotkey=R
```

provided by XiaolinFunke on discord

**Comment by modmoto** [comment]
hmm, jeah that makes sense. I guess the mutliline is the issue here.

**Comment by modmoto** [comment]
yes it is the multiline, if he removes it, it works as intended. I will message him, because dealing with newlines is not something I want to do ;) thanks for the report!

**Comment by Qeenon** [comment]
@modmoto I'd keep it open with low priority.
Maybe someone will code support for multiline unless it's something extremely hard or impossible to do.
