### ISSUE TITLE
Problems with grouping ingame at start

### ISSUE THREAD

**Issue by ringelnet** [w3champions/launcher#93]
Hey,
when I start Wc3 through w3c i have the hotkeys set up by w3c. When I start a game my key bindings for making groups never work. All hotkeys are ok but i cant group like buildings to 4, 5 ,6 etc. Its not working. I have to go to desktop and click the button "inventory hotkeys are on" in the hotkey section at the w3c setup. The color was green before and stays green. When I clicked it (nothing visual changes) and get back ingame, the grouping works. 
I have to do that every game, it doesnt stay active. I dunno why. Didnt had it before. I used custom hotkeys before in wc3. 

Any help?

**Comment by modmoto** [comment]
Hi, 

thanks for the report. Unfortunatelly right now I have very limited time. I moved it to the correct repo and hope to be able to do this soon.

Thanks!

**Comment by modmoto** [comment]
Hey, version 14.5 solves this, hope this is working now for you =)
