### ISSUE TITLE
linux/wine: YOU CANNOT JOIN FLO GAMES

### ISSUE THREAD

**Issue by sim590** [w3champions/launcher#94]
![cannotjoin](https://user-images.githubusercontent.com/4147254/112741383-65541980-8f53-11eb-8665-877c764c089e.png)

So I have installed the app fine. The launcher starts up fine and I can remap my keys and everything. Now, when I go into "W3CHAMPIONS" button and try to search for a FLO game, I get the error message up there.

Bonjour did install before this, so this is not about Bonjour not being installed. But there's something that doesn't work during connection establishment somehow, I guess.

Now, I don't expect w3champions to support wine necessarily, but I would have liked if you could help me debugging this. I would like to look at some logs and give you at least more information in the hope to find a solution or a workaround.

I have looked at logs in

```
C:\users\simon\Application Data\w3champions\logs\
```

but I didn't get valuable information. Here are the files if that could help:

[main.log](https://github.com/w3champions/launcher/files/6216810/main.log)
[renderer.log](https://github.com/w3champions/launcher/files/6216806/renderer.log)

Please let me know about any way I can provide more valuable information.

## My setup

* **wine version**: wine-6.4 (Staging)
* **dll overrides**: d3d11, dxgi (built-in)
* **OS**: ArchLinux
* **w3champions version**: 21
* **w3champions launcher version**: 0.14.5

**Comment by abeninski** [comment]
Can you try now

**Comment by modmoto** [comment]
Hi Sim,

as you pointed out, we dont support wine. But from the logs I dont see any obvious issues, like here

```[2021-03-27 23:10:00.871] [info] Connected to flo worker websocket on 45891```

 The Launcher and WC3 are talking to each other via websockets. Is this getting blocked by Wine maybe? There was an issue where a guy managed to set up wine and w3c https://github.com/w3champions/launcher/issues/95 maybe you can contact him and ask what hoops he had to jump through?

If you figure it out, I would happily write a how to for this repo.

**Comment by modmoto** [comment]
Ahh, abe was a second faster ^^

**Comment by Qeenon** [comment]
you need older wine, before bonjour changes

**Comment by sim590** [comment]
> Can you try now

I just tried it again, and I got the same message.

**Comment by sim590** [comment]
> you need older wine, before bonjour changes

I will try that!

**Comment by sim590** [comment]
@Qeenon: I've looked at `git log` in https://github.com/wine-mirror/wine, but I didn't see any mention of `[bB]onjour`. Do you know what version would be good to try?

**Comment by Qeenon** [comment]
@sim590 search on #linux channel on discord

**Comment by SmirnovAlexander** [comment]
any updates?
it is impossible to play now because playing w/ flo is the only option left

**Comment by Miezhiko** [comment]
moved issue there https://github.com/w3champions/flo
