### ISSUE TITLE
Launcher is Kind of Hard to Run on Linux

### ISSUE THREAD

**Issue by KoryMac** [w3champions/launcher#95]
Manual install into a warcraft 3 wine prefix works fine
Getting the launcher to work is quite a bit trickier; I haven't been able to use it yet
Because of this Flo is unavailable to me
Not sure what would be required to port the w3c launcher to Linux, or how it would interact with Warcraft III running through WINE
Choosing to not support a platform that is also not supported by the game for which this service was made is reasonable. It would be cool to have Flo on Linux though

**Comment by NiSchie** [comment]
@KoryMac can you explain how you managed to get it to run? Im running into the same problem.
